---
title: "Sampling demonstration"
author: "Lukáš Hejtmánek"
date: "8 October 2018"
output: github_document
---

```{r setup, include=FALSE}
library(ggplot2)
library(dplyr)
library(knitr)
normal <-  c(3,4,5,5,5,6,7)
normal_shifted <- c(5,6,7,7,7,8,9)
extremes <- c(1,1,2,5,8,10,10)
bias_extremes <- c(1,1,4,5,6,8,8)
missing <- c(3,NA,5,5,NA,6,NA)
N <- 7
types <- c(rep("normal", 7), 
           rep("normal_shifted", 7), 
           rep("extremes", 7), 
           rep("bias_extremes", 7), 
           rep("missing", 7))

values <- c(normal, normal_shifted, extremes, bias_extremes, missing)
mean(values, na.rm = T)

df <- data.frame(value=values, type=types)

sample_data <- function(data, n_sample){
  selected <- c()
  for(i in 0:4){
    selected <- c(selected, sample(1:N, n_sample) + N*i)
  }
  sampled_data <- data[selected,]
  ls <- list()
  ls$mean <- mean(sampled_data$value, na.rm = T)
  ls$mean_plot <- ggplot(sampled_data, aes(type, value, fill=type)) + stat_summary(fun.y="mean", geom="bar") + 
    stat_summary(geom = "errorbar", fun.data = mean_se, position = "dodge", width=0.2) + 
    guides(fill=FALSE)
  ls$hist_plot <- ggplot(sampled_data, aes(value, fill=type)) + geom_histogram(bins=50) + geom_density(aes(y=..density..*5)) + 
    facet_wrap(~type) + geom_vline(xintercept = ls$mean) + guides(fill=FALSE)
  ls$data <- sampled_data
  return(ls)
}
ls_all <- sample_data(df, 7)
```

# Basic descriptors


So in our case we have a mean `r ls_all$mean` and a following distribution.

```{r, echo=F, warning=F}
ls_all$mean_plot
true_mean <- ls_all$data %>% group_by(type) %>%  summarize(true_mean=mean(value, na.rm = T))
kable(true_mean)
```

looking at each separately, we get 

```{r, echo=F, message=F, warning=F}
ls_all$hist_plot
```


## Sampling
Sampling two poker chips
```{r, echo=F, message=F, warning=F}
ls_2 <- list()
n_sample <-  2
df_2_all_data <- data.frame(value=c(), type=c(), sample=c())
for(i in 1:100){
  ls_2[[i]] <- sample_data(df,n_sample)
  new_data <- ls_2[[i]]$data
  new_data$sample <- rep(i, n_sample)
  df_2_all_data <- rbind(df_2_all_data, new_data)
}
```

Let's have a look at the means of those 100 samples of 10 percent of data
```{r, echo=F, message=F, warning=F}
means_2 <- df_2_all_data %>% group_by(sample, type) %>% summarize(mean=mean(value, na.rm=T))
ggplot(means_2, aes(mean, fill=type)) + geom_histogram(bins=30) + facet_wrap(~type) + guides(fill=F)
true_mean
range_2 <- means_2 %>% group_by(type) %>% summarize(min=min(mean, na.rm = T), max = max(mean, na.rm=T), mean=mean(mean, na.rm=T))
range_2 <- merge(range_2, true_mean, by="type")
kable(range_2)
```

### Sampling 4 poker chips
```{r, echo=F, message=F, warning=F}
ls_2 <- list()
n_sample <-  4
df_2_all_data <- data.frame(value=c(), type=c(), sample=c())
for(i in 1:100){
  ls_2[[i]] <- sample_data(df,n_sample)
  new_data <- ls_2[[i]]$data
  new_data$sample <- rep(i, n_sample)
  df_2_all_data <- rbind(df_2_all_data, new_data)
}
```

Let's have a look at the means of those 100 samples of 10 percent of data
```{r, echo=F, message=F, warning=F}
means_2 <- df_2_all_data %>% group_by(sample, type) %>% summarize(mean=mean(value, na.rm=T))
ggplot(means_2, aes(mean, fill=type)) + geom_histogram(bins=30) + facet_wrap(~type) + guides(fill=F)
range_2 <- means_2 %>% group_by(type) %>% summarize(min=min(mean, na.rm = T), max = max(mean, na.rm=T), mean=mean(mean, na.rm=T))
range_2 <- merge(range_2, true_mean, by="type")
kable(range_2)
```
